version: '2'

services:
  seq:
    image: datalust/seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 9051:80 # UI
      - 5342:5341 # Data ingest
    volumes:
      - seq_data:/data

volumes:
  seq_data:


