version: '3.2'
services:     
  databaseMsSql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Abc!1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - 16122:1433
    networks:
      - directus
    volumes:
      - mssql_system:/var/opt/mssql
      - mssql_user:/var/opt/sqlserver
      - c:/temp:/temp    

  redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    networks:
      - directus
    volumes:
      - ./redis/config:/etc/redis
      - ./redis/storage:/data
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  directus:
    container_name: directus
    image: directus/directus:v9.0.0-rc.51
    ports:
      - 8055:8055
    networks:
      - directus
    depends_on:
      - redis
      - databaseMsSql
    volumes:
      - ./directus/data:/directus/uploads
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'mssql'
      DB_HOST: 'databaseMsSql'
      DB_PORT: '1433'
      DB_DATABASE: 'directus'
      DB_USER: 'sa'
      DB_PASSWORD: 'Abc!1234'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://redis:6379'

      ADMIN_EMAIL: 'mfe@world-direct.at'
      ADMIN_PASSWORD: 'password'


  mesh:
    image: "gentics/mesh-demo:latest"
    ports:
      - 8085:8080

networks:
  directus:
  squidex:
    
volumes:
  mssql_system:
  mssql_user: