version: '2'

services:
  redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/config:/etc/redis
      - ./redis/storage:/data
    command: [ "redis-server", "/etc/redis/redis.conf" ]



