version: '3.2'

services:
  redis:
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    networks:
      - directus
    volumes:
      - ./redis/config:/etc/redis
      - ./redis/storage:/data
    command: [ "redis-server", "/etc/redis/redis.conf" ]

  databaseMsSql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Abc!1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - 16122:1433
    networks:
      - directus
    volumes:
      - mssql_system:/var/opt/mssql
      - mssql_user:/var/opt/sqlserver
      - c:/temp:/temp

  directus:
    image: directus/directus:v9.0.0-rc.51
    ports:
      - 8055:8055
    networks:
      - directus
    environment:
      KEY: '5AB85FAB-9A9A-4D97-99F8-6AFABB65ECB3'
      SECRET: 'B253FEC5-1682-4D3A-9BCB-754A388CC987'

      DB_CLIENT: 'mssql'
      DB_HOST: 'databaseMsSql'
      DB_PORT: '1433'
      DB_DATABASE: 'directus'
      DB_USER: 'sa'
      DB_PASSWORD: "Abc!1234"

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'mfe@world-direct.at'
      ADMIN_PASSWORD: 'password'

networks:
  directus:

volumes:
  mssql_system:
  mssql_user:


